#include "Shared.h"
#include "ui/RaidGuide.h"
#include "data/WingData.h"
#include "data/QuickPlayData.h"
#include "icon_png.h"  // auto-generated by gen_icon.py

AddonAPI_t*       APIDefs  = nullptr;
AddonDefinition_t AddonDef = {};

// Nexus identifier strings — must be consistent across Add/Remove calls
static constexpr const char* kTexIcon     = "ICON_RAIDGUIDE";
static constexpr const char* kKeybind     = "KB_RAIDGUIDE_TOGGLE";
static constexpr const char* kQuickAccess = "QA_RAIDGUIDE";

static void OnKeybind(const char* /*aIdentifier*/, bool aIsRelease)
{
    if (!aIsRelease) RaidGuide::Toggle();
}

void AddonLoad(AddonAPI_t* aAPI)
{
    APIDefs = aAPI;
    InitQuickPlayData();
    InitIcebroodStrikeData();
    InitWingData();

    // Bake the embedded icon into a Nexus-managed texture.
    // §17 (LESSONS_LEARNED): Textures_GetOrCreateFromURL is unreliable;
    // loading from memory is the reliable path.
    APIDefs->Textures_GetOrCreateFromMemory(
        kTexIcon,
        const_cast<unsigned char*>(icon_png),
        static_cast<uint64_t>(icon_png_len));

    // Register a rebindable keybind (default: ALT+SHIFT+R).
    // The user can change it in Nexus → Options → Addons → Keybinds.
    APIDefs->InputBinds_RegisterWithString(kKeybind, OnKeybind, "ALT+SHIFT+R");

    // Add our icon to the Nexus quick-access bar.
    // Clicking it or pressing the keybind calls OnKeybind → RaidGuide::Toggle().
    APIDefs->QuickAccess_Add(
        kQuickAccess,
        kTexIcon,   // normal state texture
        kTexIcon,   // hover state texture (same icon — swap for a brighter variant if desired)
        kKeybind,
        "Raid Training Guide");

    // Register render callbacks
    APIDefs->GUI_Register(RT_Render, RaidGuide::Render);
    APIDefs->GUI_Register(RT_OptionsRender, RaidGuide::RenderOptions);
}

void AddonUnload()
{
    APIDefs->GUI_Deregister(RaidGuide::Render);
    APIDefs->GUI_Deregister(RaidGuide::RenderOptions);
    APIDefs->InputBinds_Deregister(kKeybind);
    APIDefs->QuickAccess_Remove(kQuickAccess);
    APIDefs = nullptr;
}

extern "C" __declspec(dllexport) AddonDefinition_t* GetAddonDef()
{
    AddonDef.Signature   = 0x52474D30; /* "RGM0" — replace with your own unique ID */
    AddonDef.APIVersion  = NEXUS_API_VERSION;
    AddonDef.Name        = "Raid Training Guide";
    AddonDef.Version     = { 1, 0, 0, 0 };
    AddonDef.Author      = "Todd0042";
    AddonDef.Description = "In-game mechanic reference for all raid wings.";
    AddonDef.Load        = AddonLoad;
    AddonDef.Unload      = AddonUnload;
    AddonDef.Flags       = AF_None;
    AddonDef.Provider    = UP_GitHub;
    AddonDef.UpdateLink  = "https://github.com/Todd0042/gw2-raid-guide";
    return &AddonDef;
}

BOOL APIENTRY DllMain(HMODULE, DWORD, LPVOID) { return TRUE; }
